import { 
  UserProfile, EmailAddress, Message, CreditPackage, 
  CreditTransaction, Payment, AuditLog, CompatibilityItem 
} from '@/types';

export const INITIAL_PACKAGES: CreditPackage[] = [
  {
    id: 'pkg-1',
    name: 'Starter Pack',
    price: 150,
    currency: 'BDT',
    credits: 100,
    bonus: 10,
    status: 'active',
    description: 'Perfect for quick verifications, personal testing, and occasional signups.',
    features: ['110 Total Credits', 'Instant OTP detection', 'Valid for 30 days', 'Standard delivery speed'],
    is_featured: false,
    display_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pkg-2',
    name: 'Pro Tester',
    price: 350,
    currency: 'BDT',
    credits: 300,
    bonus: 50,
    status: 'active',
    description: 'Our most popular choice for developers, QA engineers, and automated testing.',
    features: ['350 Total Credits', 'Priority email intake', 'High-accuracy OTP extraction', 'Telegram notifications', 'Multi-device sync'],
    is_featured: true,
    display_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: 'pkg-3',
    name: 'Enterprise Scale',
    price: 800,
    currency: 'BDT',
    credits: 800,
    bonus: 200,
    status: 'active',
    description: 'High-throughput solution for QA agencies, growth teams, and power users.',
    features: ['1,000 Total Credits', 'Custom catch-all routing', 'Developer API access', 'Dedicated priority queue', '24/7 Priority support'],
    is_featured: false,
    display_order: 3,
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-admin-1',
    name: 'OmniBey Admin',
    email: 'admin@omnibey.com',
    phone: '+8801711000000',
    role: 'admin',
    credits: 9999,
    account_status: 'active',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'user-demo-1',
    name: 'Alex Rivera',
    email: 'user@omnibey.com',
    phone: '+8801822334455',
    role: 'user',
    credits: 45,
    account_status: 'active',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_EMAILS: EmailAddress[] = [
  {
    id: 'email-1',
    user_id: 'user-demo-1',
    email_address: 'quickbox47@omnibey.com',
    prefix: 'quickbox47',
    domain: 'omnibey.com',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
    expires_at: new Date(Date.now() + 45 * 60000).toISOString(),
    status: 'active',
    usage_count: 3,
    message_count: 2,
    otp_count: 1,
    last_message_at: new Date(Date.now() - 5 * 60000).toISOString(),
    last_used_at: new Date(Date.now() - 2 * 60000).toISOString(),
    user_service_tag: 'Discord Verification',
  },
  {
    id: 'email-2',
    user_id: 'user-demo-1',
    email_address: 'verifybox82@omnibey.com',
    prefix: 'verifybox82',
    domain: 'omnibey.com',
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
    expires_at: new Date(Date.now() - 1 * 3600000).toISOString(),
    status: 'expired',
    usage_count: 1,
    message_count: 1,
    otp_count: 1,
    last_message_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    last_used_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    user_service_tag: 'Github Signup',
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    email_address_id: 'email-1',
    user_id: 'user-demo-1',
    sender: 'security@discord.com',
    recipient: 'quickbox47@omnibey.com',
    subject: 'Your Discord verification code is 482931',
    body_text: 'Hey Alex,\n\nWelcome to Discord! To finish creating your account, please enter the following verification code:\n\n482931\n\nThis code will expire in 10 minutes. If you did not make this request, you can safely ignore this email.\n\nThanks,\nThe Discord Team',
    body_html: '<div style="font-family:sans-serif;padding:20px;background:#f9f9fb;border-radius:12px;"><h2>Verify your Discord account</h2><p>Welcome to Discord! Please enter the code below to complete setup:</p><div style="font-size:28px;font-weight:bold;letter-spacing:4px;color:#5865F2;padding:16px;background:#fff;border-radius:8px;display:inline-block;">482931</div><p style="margin-top:16px;color:#666;">Expires in 10 minutes.</p></div>',
    detected_otp: '482931',
    otp_confidence: 'high',
    is_read: false,
    received_at: new Date(Date.now() - 5 * 60000).toISOString(),
  },
  {
    id: 'msg-2',
    email_address_id: 'email-1',
    user_id: 'user-demo-1',
    sender: 'notify@github.com',
    recipient: 'quickbox47@omnibey.com',
    subject: '[GitHub] Device verification code',
    body_text: 'Hello,\n\nPlease verify your login from Chrome on Windows.\n\nVerification code: 930128\n\nDon\'t give this code to anyone.',
    body_html: '<div style="font-family:sans-serif;padding:15px;"><h3>GitHub Login Verification</h3><p>Your one-time pass code is: <strong>930128</strong></p></div>',
    detected_otp: '930128',
    otp_confidence: 'high',
    is_read: true,
    received_at: new Date(Date.now() - 12 * 60000).toISOString(),
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    payment_ref: 'PAY-10291',
    user_id: 'user-demo-1',
    user_email: 'user@omnibey.com',
    user_name: 'Alex Rivera',
    package_id: 'pkg-2',
    package_name: 'Pro Tester (350 Credits)',
    amount: 350,
    currency: 'BDT',
    payment_method: 'bkash',
    sender_identifier: '01822334455',
    transaction_id: '9B48CK01Z',
    screenshot_path: 'mock/screenshot-1.png',
    screenshot_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=400&auto=format&fit=crop&q=80',
    status: 'pending',
    submitted_at: new Date(Date.now() - 25 * 60000).toISOString(),
    created_at: new Date(Date.now() - 25 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'pay-2',
    payment_ref: 'PAY-10145',
    user_id: 'user-demo-1',
    user_email: 'user@omnibey.com',
    user_name: 'Alex Rivera',
    package_id: 'pkg-1',
    package_name: 'Starter Pack (110 Credits)',
    amount: 150,
    currency: 'BDT',
    payment_method: 'nagad',
    sender_identifier: '01711998877',
    transaction_id: 'NG9918234A',
    screenshot_path: undefined,
    status: 'approved',
    submitted_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    reviewed_at: new Date(Date.now() - 3 * 86400000 + 10 * 60000).toISOString(),
    reviewed_by: 'user-admin-1',
    reviewer_name: 'OmniBey Admin',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
];

export const INITIAL_TRANSACTIONS: CreditTransaction[] = [
  {
    id: 'tx-1',
    user_id: 'user-demo-1',
    amount: 15,
    transaction_type: 'bonus',
    balance_after: 15,
    reference_id: 'welcome-bonus',
    reference_type: 'signup',
    description: 'Welcome bonus trial credits',
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'tx-2',
    user_id: 'user-demo-1',
    amount: 110,
    transaction_type: 'purchase',
    balance_after: 125,
    reference_id: 'PAY-10145',
    reference_type: 'payment',
    description: 'Purchased Starter Pack (100 credits + 10 bonus)',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'tx-3',
    user_id: 'user-demo-1',
    amount: -80,
    transaction_type: 'usage',
    balance_after: 45,
    reference_id: 'batch-generation',
    reference_type: 'email_usage',
    description: 'Temporary mailboxes usage and OTP extractions',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const INITIAL_COMPATIBILITY: CompatibilityItem[] = [
  {
    id: 'comp-1',
    service_domain: 'discord.com',
    email_domain: 'omnibey.com',
    provider: 'OmniBey',
    total_tests: 1420,
    successful_tests: 1398,
    failed_tests: 22,
    success_rate: 98.45,
    average_delivery_time: '4 seconds',
    confidence: 'High',
    last_tested: 'Just now',
    disclaimer: 'Observed historical data based on internal system telemetry; not a guarantee.',
  },
  {
    id: 'comp-2',
    service_domain: 'github.com',
    email_domain: 'omnibey.com',
    provider: 'OmniBey',
    total_tests: 980,
    successful_tests: 975,
    failed_tests: 5,
    success_rate: 99.49,
    average_delivery_time: '3 seconds',
    confidence: 'High',
    last_tested: '12 mins ago',
    disclaimer: 'Observed historical data based on internal system telemetry; not a guarantee.',
  },
  {
    id: 'comp-3',
    service_domain: 'openai.com',
    email_domain: 'omnibey.com',
    provider: 'OmniBey',
    total_tests: 810,
    successful_tests: 785,
    failed_tests: 25,
    success_rate: 96.91,
    average_delivery_time: '5 seconds',
    confidence: 'High',
    last_tested: '25 mins ago',
    disclaimer: 'Observed historical data based on internal system telemetry; not a guarantee.',
  },
  {
    id: 'comp-4',
    service_domain: 'netflix.com',
    email_domain: 'omnibey.com',
    provider: 'OmniBey',
    total_tests: 620,
    successful_tests: 580,
    failed_tests: 40,
    success_rate: 93.55,
    average_delivery_time: '7 seconds',
    confidence: 'Medium',
    last_tested: '1 hour ago',
    disclaimer: 'Observed historical data based on internal system telemetry; not a guarantee.',
  },
  {
    id: 'comp-5',
    service_domain: 'spotify.com',
    email_domain: 'omnibey.com',
    provider: 'OmniBey',
    total_tests: 510,
    successful_tests: 498,
    failed_tests: 12,
    success_rate: 97.65,
    average_delivery_time: '4 seconds',
    confidence: 'High',
    last_tested: '2 hours ago',
    disclaimer: 'Observed historical data based on internal system telemetry; not a guarantee.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    admin_id: 'user-admin-1',
    admin_email: 'admin@omnibey.com',
    action: 'payment_approved',
    target_type: 'payment',
    target_id: 'PAY-10145',
    details: { amount: 150, credits_added: 110, method: 'nagad' },
    ip_address: '103.145.74.12',
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'audit-2',
    admin_id: 'user-admin-1',
    admin_email: 'admin@omnibey.com',
    action: 'provider_status_check',
    target_type: 'email_provider',
    target_id: 'omnibey',
    details: { status: 'operational', latency_ms: 42 },
    ip_address: '103.145.74.12',
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];
